name: CD Pipeline

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
      - name: Delete Old docker container
        run: sudo docker rm -f cicd-pipeline-container || true
      - name: Remove Docker image
        run: docker rmi -f $(docker images -aq)
      - name: Pull Docker image
        run: sudo docker pull anand5394/restaurant:latest
      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 --name cicd-pipeline-container anand5394/restaurant